name: sentera-api
channels:
  - conda-forge
dependencies:
  - python=3.7
  # dev dependencies
  - pytest
  - pre_commit
  - sphinx
  - sphinx_rtd_theme
  - m2r
  - pip
  - pipenv
  - httpretty
  - requests-mock
  # main dependencies
  - requests
  - tenacity
  - pandas
  - aiohttp
  - tqdm
  - ratelimit
  # subpackage dependencies
