name: sentera-api
channels:
  - conda-forge
dependencies:
  - python=3.6
  # dev dependencies
  - pytest
  - pylint
  - sphinx
  - sphinx_rtd_theme
  - m2r
  # main dependencies
  - requests
  - jupyter
  - pandas
  - aiohttp
<<<<<<< HEAD
  - tqdm
=======
>>>>>>> 4ecc093390d2d5ca1c3d01224889510783f80cc5
  # subpackage dependencies
  # private dependencies
#  - pip
#  - pip:
#    - git+ssh://git@github.com/SenteraLLC/py-utils@v2.1.0
